apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-item-service
  template:
    metadata:
      labels:
        app: cart-item-service
    spec:
      containers:
      - name: cart-item-service
        image: your-dockerhub-username/msa_project-cart-item-service:latest
        ports:
        - containerPort: 9107
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/cartitem_service_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-item-service
spec:
  type: NodePort
  selector:
    app: cart-item-service
  ports:
    - protocol: TCP
      port: 9107
      targetPort: 9107

